### ISSUE TITLE
expect-axe-playwright is only supported with playwright test runner 

### ISSUE THREAD

**Issue by nikhilwaichal** [Widen/expect-axe-playwright#26]
Hi 
I am using cucumberjs test runner for executing the playwright test. 
I tried to integrate this package with it but when I am running the test its throwing me an error for expect statement.
test should be started in order to use expect statement

Is there a way to integrate with cucumber test runner
TIA

**Comment by mskelton** [comment]
We have no plans to support non-official test runners like jest-playwright or cucumber.  They are pretty rare compared to the official library and honestly I don't see any compelling reason not to use the official test runner.
