### ISSUE TITLE
Log details of violation(s)

### ISSUE THREAD

**Issue by ewolfe** [Widen/expect-axe-playwright#3]
How do I get insight into the violation that was thrown? There's not much in the log:

```
Error: expect(received).toBeAccessible(expected)

Expected: No violations
Received: 1 violations

Violations: list(1)

  68 |   const header = await page.$('header');
> 69 |   await expect(header).toBeAccessible();
     |                        ^
```

**Comment by mskelton** [comment]
@ewolfe Given that Playwright Test is the recommended approach for testing over Jest Playwright, our plan is to release a major version of this library that only supports Playwright Test which would allow us to attach a report file of violations that would be printed with the error.

For now, I'd recommend manually testing the page with the Axe browser extension.  That's unfortunately all I can tell you right now, but hopefully we can get that new version released soon enough.  I'm going to be making a v2 milestone for this library which I'll add this issue to.
